//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaiyaWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Users_Master
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int RowID { get; set; }
        public int UserUID { get; set; }
        public string UserID { get; set; }
        public string Pw { get; set; }
        public System.DateTime JoinDate { get; set; }
        public bool Admin { get; set; }
        public byte AdminLevel { get; set; }
        public bool UseQueue { get; set; }
        public short Status { get; set; }
        public byte Leave { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string UserType { get; set; }
        public string UserIp { get; set; }
        public string ModiIp { get; set; }
        public Nullable<System.DateTime> ModiDate { get; set; }
        public int Point { get; set; }
        public string Enpassword { get; set; }
        public string Birth { get; set; }
    }
}
